name: backend-ci

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, lint, test
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install yarn
        run: npm install -g yarn

      - name: Upgrate yarn to latest version
        run: yarn set version stable

      - name: Install packages
        run: yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: ESLint
        run: yarn lint

      - name: Unit testing
        run: yarn test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install -g yarn aws-cdk@2.13.0
      - run: yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: CDK Synthesis
        run: yarn synth
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MPESA_API_HOST: ${{ secrets.MPESA_API_HOST }}
          MPESA_API_KEY: ${{ secrets.MPESA_API_KEY }}
          MPESA_ORIGIN: ${{ secrets.MPESA_ORIGIN }}
          MPESA_PUBLIC_KEY: ${{ secrets.MPESA_PUBLIC_KEY }}
          MPESA_SERVICE_CODE: ${{ secrets.MPESA_SERVICE_CODE }}

      - name: CDK deploy
        run: yarn deploy --require-approval never
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MPESA_API_HOST: ${{ secrets.MPESA_API_HOST }}
          MPESA_API_KEY: ${{ secrets.MPESA_API_KEY }}
          MPESA_ORIGIN: ${{ secrets.MPESA_ORIGIN }}
          MPESA_PUBLIC_KEY: ${{ secrets.MPESA_PUBLIC_KEY }}
          MPESA_SERVICE_CODE: ${{ secrets.MPESA_SERVICE_CODE }}
